/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TransferForm;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Hannah
 */
public class ChooseSupplyView extends javax.swing.JPanel {

    private String userCountInput;
    private final String unit;
    private final String itemName;
    public final int id;
    /**
     * Creates new form ChooseSupplyView
     */
    public ChooseSupplyView(int id, String itemName, String unit, String count) {
        initComponents();
        
        this.id = id;
        this.itemName = itemName;
        this.unit = unit;
        unitLabel.setText(unit);
        itemLabel.setText(itemName);
        countLabel.setText(count);
        userCountInput = "0";
        
        jTextField1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.DARK_GRAY));
    }
    
    public int getSupplyID() {
        return id;
    }
    
    public float getUserCountInput() {
        return Float.parseFloat(userCountInput);
    }
    
    public String getUnit() {
        return unit;
    }
    
    public String getItemName() {
        return itemName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        unitLabel = new javax.swing.JLabel();
        itemLabel = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        itemLabel3 = new javax.swing.JLabel();

        itemLabel2.setFont(new java.awt.Font("Quicksand Book", 0, 24)); // NOI18N
        itemLabel2.setForeground(new java.awt.Color(153, 153, 153));
        itemLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        itemLabel2.setText("Count");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(955, 58));
        setMinimumSize(new java.awt.Dimension(955, 58));
        setPreferredSize(new java.awt.Dimension(955, 58));

        jTextField1.setFont(new java.awt.Font("Quicksand Book", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setBorder(null);
        jTextField1.setMaximumSize(new java.awt.Dimension(130, 25));
        jTextField1.setMinimumSize(new java.awt.Dimension(130, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(130, 25));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        unitLabel.setFont(new java.awt.Font("Quicksand Book", 0, 24)); // NOI18N
        unitLabel.setForeground(new java.awt.Color(153, 153, 153));
        unitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        unitLabel.setText("kg");
        unitLabel.setMaximumSize(new java.awt.Dimension(150, 25));
        unitLabel.setMinimumSize(new java.awt.Dimension(150, 25));
        unitLabel.setPreferredSize(new java.awt.Dimension(150, 25));

        itemLabel.setFont(new java.awt.Font("Quicksand Book", 0, 24)); // NOI18N
        itemLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemLabel.setText("Item Name");
        itemLabel.setMaximumSize(new java.awt.Dimension(410, 25));
        itemLabel.setMinimumSize(new java.awt.Dimension(410, 25));
        itemLabel.setPreferredSize(new java.awt.Dimension(410, 25));

        countLabel.setFont(new java.awt.Font("Quicksand Book", 0, 24)); // NOI18N
        countLabel.setForeground(new java.awt.Color(153, 153, 153));
        countLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countLabel.setText("Count");
        countLabel.setMaximumSize(new java.awt.Dimension(134, 25));
        countLabel.setMinimumSize(new java.awt.Dimension(134, 25));
        countLabel.setPreferredSize(new java.awt.Dimension(134, 25));

        itemLabel3.setFont(new java.awt.Font("Quicksand Book", 0, 24)); // NOI18N
        itemLabel3.setForeground(new java.awt.Color(153, 153, 153));
        itemLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemLabel3.setText("left");
        itemLabel3.setMaximumSize(new java.awt.Dimension(50, 25));
        itemLabel3.setMinimumSize(new java.awt.Dimension(50, 25));
        itemLabel3.setPreferredSize(new java.awt.Dimension(50, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        userCountInput = jTextField1.getText().trim();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
           
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        userCountInput = jTextField1.getText().trim();
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countLabel;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JLabel itemLabel2;
    private javax.swing.JLabel itemLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
}
